<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'slick' => array(
    'normal' => $fontDir . '/slick-normal_2067d3ad478a1dc2210c3286be319d0f',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome-normal_6b8fcb303bfef6f4ea9e882534054307',
  ),
  'merriweather' => array(
    '300_italic' => $fontDir . '/merriweather-300-italic_b42b62b9d9af3d875db8e5bc931cf1cd',
    'italic' => $fontDir . '/merriweather-italic_7c24f8d0c16726d2a29f74c77a5ce319',
    'bold_italic' => $fontDir . '/merriweather-bold-italic_0a5248f5911b58a66334e38409a1c157',
    '900_italic' => $fontDir . '/merriweather-900-italic_9bbdedfbe5a86271ccb74625c631a432',
    '300' => $fontDir . '/merriweather-300_fd5f72dd7a3c3cffa54a05be4cad3a89',
    'normal' => $fontDir . '/merriweather-normal_0b98653871c169c53311c1beaa5cf158',
    'bold' => $fontDir . '/merriweather-bold_ca9ec64b7e4eb8abdaec3d96d045de98',
    '900' => $fontDir . '/merriweather-900_5039f1e6d4145c9199f7ed6f3581ad9c',
  ),
  'poppins' => array(
    '300' => $fontDir . '/poppins-300_fdf63d9f742346a5ee6b70f5a8af6c01',
    'normal' => $fontDir . '/poppins-normal_c1b7381dfaadf37a84cf14d786076e6d',
    '500' => $fontDir . '/poppins-500_3ab22c79a50a7416f996a1aba688428d',
    '600' => $fontDir . '/poppins-600_270e18a84ac8b306c8f31abe1d0720fa',
    'bold' => $fontDir . '/poppins-bold_7eb29046bc7eaf66b896ec27702d038b',
    '800' => $fontDir . '/poppins-800_536163191f53b5da319f92ee38a84645',
    '900' => $fontDir . '/poppins-900_2cd47d9ee4ef8f23390bc44c05a7b082',
  ),
) ?>